[env]
REDIS_URL="redis://localhost/"
DATABASE_URL="postgresql://ksoxuser:ksoxuserp4ssword@localhost/ksox"
TESTS_CASES="1000000"
TESTS_FRACTION_BYTES="2"
BLOCK_CONFIRMATIONS="10"
PRIVATE_KEY="637cf0cb529ff41499db61e0913674570ebd68c9d7c9a7a021cffd3c02c85427"