apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: ksox-finance
  labels:
    app: postgres-database
spec:
  selector:
    matchLabels:
      app: postgres-database
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres-database
          image: registry.internal.visoft.solutions/postgres-database
          envFrom:
            - configMapRef:
                name: settings
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-pv
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ksox-finance
spec:
  selector:
    app: postgres-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
