services:
  postgres:
    container_name: ksox-postgres
    hostname: ksox-postgres
    image: postgres
    environment:
      - POSTGRES_USER=ksoxuser
      - POSTGRES_PASSWORD=ksoxuserp4ssword
      - POSTGRES_DB=ksox
    ports:
      - "5432:5432"

  server:
    container_name: ksox-server
    hostname: ksox-server
    build:
      context: server
    depends_on:
      - postgres
  
  # engine:
  #   container_name: ksox-engine
  #   hostname: ksox-engine
  #   build:
  #     context: server/engine

  redis:
    container_name: ksox-redis
    hostname: ksox-redis
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    
  worker:
    container_name: ksox-worker
    hostname: ksox-worker
    build:
      context: server/worker
    depends_on:
      - redis
  
  web:
    container_name: ksox-web
    hostname: ksox-web
    build:
      context: web
    depends_on:
      - worker
  
  proxy:
    container_name: ksox-proxy
    hostname: ksox-proxy
    build:
      context: proxy
    depends_on:
      - worker
      - web
    ports:
      - 7979:80
