services:
  postgres:
    container_name: ksox-postgres
    hostname: ksox-postgres
    build:
      context: postgres
    environment:
      - POSTGRES_USER=ksoxuser
      - POSTGRES_PASSWORD=ksoxuserp4ssword
      - POSTGRES_DB=ksox
    ports:
      - 5432:5432

  redis:
    container_name: ksox-redis
    hostname: ksox-redis
    build:
      context: redis
    ports:
      - 6379:6379
      - 8001:8001

  server-engine:
    container_name: ksox-server-engine
    hostname: ksox-server-engine
    build:
      context: server
      dockerfile: ./engine.dockerfile
    environment:
      - DATABASE_URL=postgresql://ksoxuser:ksoxuserp4ssword@ksox-postgres/ksox
      - REDIS_URL=redis://ksox-redis/
    depends_on:
      - postgres
      - redis

  server-engagement:
    container_name: ksox-server-engagement
    hostname: ksox-server-engagement
    build:
      context: server
      dockerfile: ./engagement.dockerfile
    environment:
      - DATABASE_URL=postgresql://ksoxuser:ksoxuserp4ssword@ksox-postgres/ksox
      - REDIS_URL=redis://ksox-redis/
    depends_on:
      - postgres
      - redis
  
  server-worker:
    container_name: ksox-server-worker
    hostname: ksox-server-worker
    build:
      context: server
      dockerfile: ./worker.dockerfile
    environment:
      - DATABASE_URL=postgresql://ksoxuser:ksoxuserp4ssword@ksox-postgres/ksox
      - ENGINE_URL=http://ksox-server-engine/
      - BLOCKCHAIN_URL=http://ksox-server-blockchain/
      - REDIS_URL=redis://ksox-redis/
      - RUST_BACKTRACE=full
    depends_on:
      - postgres
      - redis
      - server-engine
      - server-blockchain
  
  server-blockchain:
    container_name: ksox-server-blockchain
    hostname: ksox-server-blockchain
    build:
      context: server
      dockerfile: ./blockchain.dockerfile
    environment:
      - DATABASE_URL=postgresql://ksoxuser:ksoxuserp4ssword@ksox-postgres/ksox
      - ENGINE_URL=http://ksox-server-engine/
      - WS_PROVIDER_URL=wss://eth-sepolia.g.alchemy.com/v2/-koG9fJPMpiL7ywoOZyGtWlLZ_JymCb2
      - CONTRACT_ADDRESS=0x8edCD44edF2C5391B418a2b9d3194eDDa6253303
      - CONTRACT_PRIVATE_KEY=637cf0cb529ff41499db61e0913674570ebd68c9d7c9a7a021cffd3c02c85427
    depends_on:
      - postgres
      - redis
      - server-engine

  web-exchange:
    container_name: ksox-web-exchange
    hostname: ksox-web-exchange
    build:
      context: web
      dockerfile: ./exchange.dockerfile
    depends_on:
      - server-worker

  web-exchange-landing:
    container_name: ksox-web-exchange-landing
    hostname: ksox-web-exchange-landing
    build:
      context: web
      dockerfile: ./exchange-landing.dockerfile
    depends_on:
      - server-worker

  web-processor:
    container_name: ksox-web-processor
    hostname: ksox-web-processor
    build:
      context: web
      dockerfile: ./processor.dockerfile
    depends_on:
      - server-worker

  web-dashboard:
    container_name: ksox-web-dashboard
    hostname: ksox-web-dashboard
    build:
      context: web
      dockerfile: ./dashboard.dockerfile
    depends_on:
      - server-worker

  proxy:
    container_name: ksox-proxy
    hostname: ksox-proxy
    build:
      context: proxy
    depends_on:
      - server-worker
      - web-exchange
      - web-exchange-landing
      - web-processor
      - web-dashboard
      # - processor-landing
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
