services:
  postgres:
    container_name: ksox-postgres
    hostname: ksox-postgres
    build:
      context: postgres
    environment:
      - POSTGRES_USER=ksoxuser
      - POSTGRES_PASSWORD=ksoxuserp4ssword
      - POSTGRES_DB=ksox
    ports:
      - 5432:5432

  redis:
    container_name: ksox-redis
    hostname: ksox-redis
    build:
      context: redis
    ports:
      - 6379:6379
      - 8001:8001

  engine:
    container_name: ksox-engine
    hostname: ksox-engine
    build:
      context: server
      dockerfile: ./engine.dockerfile
    environment:
      - DATABASE_URL=postgresql://ksoxuser:ksoxuserp4ssword@ksox-postgres/ksox
      - REDIS_URL=redis://ksox-redis/
      - ENGINE_FRACTION_ACCURACY=1/10000
    depends_on:
      - postgres
      - redis

  worker:
    container_name: ksox-worker
    hostname: ksox-worker
    build:
      context: server
      dockerfile: ./worker.dockerfile
    environment:
      - DATABASE_URL=postgresql://ksoxuser:ksoxuserp4ssword@ksox-postgres/ksox
      - ENGINE_URL=http://ksox-engine/
      - REDIS_URL=redis://ksox-redis/
      - WORKER_FRACTION_ACCURACY=1/10000
    depends_on:
      - postgres
      - redis
      - engine
    ports:
      - 7979:80

  ksox-app:
    container_name: ksox-app
    hostname: ksox-app
    build:
      context: web/ksox-app
    depends_on:
      - worker

  ksox-landing:
    container_name: ksox-landing
    hostname: ksox-landing
    build:
      context: web/ksox-landing
    depends_on:
      - worker

  processor-app:
    container_name: processor-app
    hostname: processor-app
    build:
      context: web/processor-app
    depends_on:
      - worker

  # processor-landing:
  #   container_name: processor-landing
  #   hostname: processor-landing
  #   build:
  #     context: web/processor-landing
  #   depends_on:
  #     - worker

  proxy:
    container_name: ksox-proxy
    hostname: ksox-proxy
    build:
      context: proxy
    depends_on:
      - worker
      - ksox-app
      - ksox-landing
      - processor-app
      # - processor-landing
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
