services:
  postgres:
    container_name: ksox-postgres
    hostname: ksox-postgres
    image: postgres
    environment:
      - POSTGRES_USER=ksoxuser
      - POSTGRES_PASSWORD=ksoxuserp4ssword
      - POSTGRES_DB=ksox
    ports:
      - "5432:5432"

  server:
    container_name: ksox-server
    hostname: ksox-server
    build:
      context: server
    depends_on:
      - postgres
  
  web:
    container_name: ksox-web
    hostname: ksox-web
    build:
      context: web
    depends_on:
      - server
  
  proxy:
    container_name: ksox-proxy
    hostname: ksox-proxy
    build:
      context: proxy
    depends_on:
      - server
      - web
    ports:
      - 8080:80
