services:
  blockchain:
    container_name: ksox-blockchain
    hostname: ksox-blockchain
    build:
      context: ./blockchain
    ports:
      - 8545:8545

  postgres:
    container_name: ksox-postgres
    hostname: ksox-postgres
    build:
      context: ./postgres
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432

  redis:
    container_name: ksox-redis
    hostname: ksox-redis
    build:
      context: ./redis
    env_file:
      - ./redis/.env
    ports:
      - 6379:6379
      - 8001:8001

  server-engagement:
    container_name: ksox-server-engagement
    hostname: ksox-server-engagement
    build:
      context: ./server
      dockerfile: ./engagement.dockerfile
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis

  server-engine:
    container_name: ksox-server-engine
    hostname: ksox-server-engine
    build:
      context: ./server
      dockerfile: ./engine.dockerfile
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis

  server-blockchain:
    container_name: ksox-server-blockchain
    hostname: ksox-server-blockchain
    build:
      context: ./server
      dockerfile: ./blockchain.dockerfile
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis
      - server-engine

  server-worker:
    container_name: ksox-server-worker
    hostname: ksox-server-worker
    build:
      context: ./server
      dockerfile: ./worker.dockerfile
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis
      - server-engine
      - server-blockchain
    ports:
      - 8080:80

  web-exchange:
    container_name: ksox-web-exchange
    hostname: ksox-web-exchange
    build:
      context: ./web
      dockerfile: ./exchange.dockerfile
    depends_on:
      - server-worker

  web-exchange-landing:
    container_name: ksox-web-exchange-landing
    hostname: ksox-web-exchange-landing
    build:
      context: ./web
      dockerfile: ./exchange-landing.dockerfile
    depends_on:
      - server-worker

  web-processor:
    container_name: ksox-web-processor
    hostname: ksox-web-processor
    build:
      context: ./web
      dockerfile: ./processor.dockerfile
    depends_on:
      - server-worker

  web-dashboard:
    container_name: ksox-web-dashboard
    hostname: ksox-web-dashboard
    build:
      context: ./web
      dockerfile: ./dashboard.dockerfile
    depends_on:
      - server-worker

  proxy:
    container_name: ksox-proxy
    hostname: ksox-proxy
    build:
      context: ./proxy
    depends_on:
      - server-engagement
      - server-engine
      - server-blockchain
      - server-worker
      - web-exchange
      - web-exchange-landing
      - web-processor
      - web-dashboard
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
