apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
  - image: postgres-database
    context: ./postgres
    docker:
      dockerfile: Dockerfile
  - image: redis-database
    context: ./redis
    docker:
      dockerfile: Dockerfile
  - image: server-engine
    context: ./server
    docker:
      dockerfile: engine.dockerfile
  - image: server-worker
    context: ./server
    docker:
      dockerfile: worker.dockerfile
  - image: web-app
    context: ./web/app
    docker:
      dockerfile: Dockerfile
  - image: web-landing
    context: ./web/landing
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./k8s/*
    - ./postgres/k8s/*
    - ./redis/k8s/*
    - ./server/k8s/*
    - ./web/app/k8s/*
    - ./web/landing/k8s/*
