apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
  - image: busybox
    context: ./containers
    docker:
      dockerfile: busybox.dockerfile
  - image: test-blockchain
    context: ./blockchain
    docker:
      dockerfile: Dockerfile
  - image: postgres-database
    context: ./postgres
    docker:
      dockerfile: Dockerfile
  - image: redis-database
    context: ./redis
    docker:
      dockerfile: Dockerfile
  - image: server-engine
    context: ./server
    docker:
      dockerfile: engine.dockerfile
  - image: server-worker
    context: ./server
    docker:
      dockerfile: worker.dockerfile
  - image: web-ksox-app
    context: ./web/ksox-app
    docker:
      dockerfile: Dockerfile
  - image: web-ksox-landing
    context: ./web/ksox-landing
    docker:
      dockerfile: Dockerfile
  - image: web-processor-app
    context: ./web/processor-app
    docker:
      dockerfile: Dockerfile
  - image: web-processor-landing
    context: ./web/processor-landing
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./k8s/*
    - ./blockchain/k8s/*
    - ./postgres/k8s/*
    - ./redis/k8s/*
    - ./server/k8s/*
    - ./web/ksox-app/k8s/*
    - ./web/ksox-landing/k8s/*
    - ./web/processor-app/k8s/*
    - ./web/processor-landing/k8s/*
