apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
    - image: registry.internal.visoft.solutions/blockchain-node
      context: ./blockchain
      docker:
        dockerfile: Dockerfile
    - image: registry.internal.visoft.solutions/busybox
      context: ./containers
      docker:
        dockerfile: busybox.dockerfile
    - image: registry.internal.visoft.solutions/postgres-database
      context: ./postgres
      docker:
        dockerfile: Dockerfile
    - image: registry.internal.visoft.solutions/redis-database
      context: ./redis
      docker:
        dockerfile: Dockerfile
    - image: registry.internal.visoft.solutions/server-blockchain
      context: ./server
      docker:
        dockerfile: blockchain.dockerfile
    - image: registry.internal.visoft.solutions/server-engine
      context: ./server
      docker:
        dockerfile: engine.dockerfile
    - image: registry.internal.visoft.solutions/server-engagement
      context: ./server
      docker:
        dockerfile: engagement.dockerfile
    - image: registry.internal.visoft.solutions/server-worker
      context: ./server
      docker:
        dockerfile: worker.dockerfile
    - image: registry.internal.visoft.solutions/pay-worker
      context: ./server
      docker:
        dockerfile: worker.dockerfile
    - image: registry.internal.visoft.solutions/web-exchange
      context: ./web
      docker:
        dockerfile: exchange.dockerfile
    - image: registry.internal.visoft.solutions/web-exchange-landing
      context: ./web
      docker:
        dockerfile: exchange-landing.dockerfile
    - image: registry.internal.visoft.solutions/web-processor
      context: ./web
      docker:
        dockerfile: processor.dockerfile
    - image: registry.internal.visoft.solutions/web-dashboard
      context: ./web
      docker:
        dockerfile: dashboard.dockerfile
manifests:
  rawYaml:
    - ./blockchain/k8s/*
    - ./postgres/k8s/*
    - ./redis/k8s/*
    - ./server/k8s/*
    - ./web/k8s/*
