[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.68"
axum = { version = "0.6.1", features = ["http2"] }
futures = "0.3.25"
serde = "1.0.152"
sqlx = "0.6.2"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["full"] }
tokio-stream = "0.1.11"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
