[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.68"
database = { path = "../database" }
linked-hash-map = "0.5.6"
prost = "0.11.6"
serde = "1.0.152"
tokio = { version = "1.23.0", features = ["full"] }
tokio-stream = "0.1.11"
tonic = "0.8.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[build-dependencies]
tonic-build = "0.8.4"
