[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-stream = "0.3.5"
axum = { version = "0.6.15", features = ["http2", "tracing", "macros"] }
futures = "0.3.25"
hyper = { version = "0.14.26", features = ["full"] }
num-bigint = { version = "0.4.3", features = ["serde", "arbitrary", "quickcheck"] }
num-derive = "0.3.3"
num-rational = { version = "0.4.1", features = ["serde"] }
num-traits = "0.2.15"
proptest = "1.1.0"
proptest-derive = "0.3.0"
prost = "0.11.6"
seq-macro = "0.3.3"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.95"
sqlx = { version = "0.6.3", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "offline",
    "uuid",
    "bigdecimal",
    "chrono"
] }
thiserror = "1.0.24"
tokio = { version = "1.23.0", features = ["full"] }
tokio-stream = "0.1.11"
tonic = "0.8.3"
tower = "0.4.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[build-dependencies]
tonic-build = "0.8.4"

[package.metadata.cargo-udeps.ignore]
normal = ["proptest", "proptest-derive", "seq-macro"]
