[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.68"
database = { path = "../database" }
futures = "0.3.25"
num-bigint = { version = "0.4.3", features = ["serde"] }
prost = "0.11.6"
serde = "1.0.152"
thiserror = "1.0.24"
tokio = { version = "1.23.0", features = ["full"] }
tokio-stream = "0.1.11"
tonic = "0.8.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
uuid = { version = "1.2.2", features = ["v4", "serde"] }

[build-dependencies]
tonic-build = "0.8.4"
