apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-exchange-deployment
  namespace: prod-ksox-finance
  labels:
    app: web-exchange
spec:
  selector:
    matchLabels:
      app: web-exchange
  template:
    metadata:
      labels:
        app: web-exchange
    spec:
      containers:
        - name: web-exchange
          image: web-exchange
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-exchange-service
  namespace: prod-ksox-finance
spec:
  selector:
    app: web-exchange
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: web-exchange-route
  namespace: prod-ksox-finance
spec:
  parentRefs:
    - name: prod-gateway
      namespace: prod
  hostnames:
    - app.ksox.finance
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - name: web-exchange-service
        port: 80
