apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-exchange-landing-deployment
  namespace: prod-ksox-finance
  labels:
    app: web-exchange-landing
spec:
  selector:
    matchLabels:
      app: web-exchange-landing
  template:
    metadata:
      labels:
        app: web-exchange-landing
    spec:
      containers:
        - name: web-exchange-landing
          image: web-exchange-landing
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 1000Mi
              cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: web-exchange-landing-service
  namespace: prod-ksox-finance
spec:
  selector:
    app: web-exchange-landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: web-exchange-landing-route
  namespace: prod-ksox-finance
spec:
  parentRefs:
    - name: prod-gateway
      namespace: prod
  hostnames:
    - ksox.finance
    - www.ksox.finance
  rules:
    - backendRefs:
      - name: web-exchange-landing-service
        port: 80