apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-processor-deployment
  namespace: prod-ksox-finance
  labels:
    app: web-processor
spec:
  selector:
    matchLabels:
      app: web-processor
  template:
    metadata:
      labels:
        app: web-processor
    spec:
      containers:
        - name: web-processor
          image: web-processor
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-processor-service
  namespace: prod-ksox-finance
spec:
  selector:
    app: web-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: web-exchange-route
  namespace: prod-ksox-finance
spec:
  parentRefs:
    - name: prod-gateway
      namespace: prod
  hostnames:
    - pay.ksox.finance
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: web-processor-service
          port: 80
