apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-ksox-finance-cert
spec:
  secretName: prod-ksox-finance-tls
  dnsNames:
    - ksox.finance
    - www.ksox.finance
    - app.ksox.finance
    - pay.ksox.finance
    - dashboard.ksox.finance
  issuerRef:
    name: prod-letsencrypt-http01
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-ksox-exchange-cert
spec:
  secretName: prod-ksox-exchange-tls
  dnsNames:
    - ksox.exchange
    - www.ksox.exchange
  issuerRef:
    name: prod-letsencrypt-http01
