apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ksox-exchange
spec:
  secretName: ksox-exchange-tls
  dnsNames:
    - ksox.exchange
    - www.ksox.exchange
    - test-blockchain.ksox.exchange
  issuerRef:
    name: ksox-exchange-issuer
