apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ksox-finance-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pavlnowak@gmail.com
    privateKeySecretRef:
      name: ksox-finance-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: ingress-nginx
      selector:
        dnsZones:
        - ksox.finance
# ---
# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: ksox-finance-issuer-selfsigned
# spec:
#   selfSigned: {}
