apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ksox-finance-letsencrypt-http01
  namespace: ksox-finance
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pavlnowak@gmail.com
    privateKeySecretRef:
      name: ksox-finance-issuer-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
        selector:
          dnsZones:
            - ksox.finance
