apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ksox-exchange-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pavlnowak@gmail.com
    privateKeySecretRef:
      name: ksox-exchange-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: ingress-nginx
      selector:
        dnsZones:
        - ksox.exchange
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ksox-exchange
spec:
  secretName: ksox-exchange-tls
  dnsNames:
    - ksox.exchange
    - www.ksox.exchange
  issuerRef:
    name: ksox-exchange-issuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-ingress
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.ksox.finance
spec:
  tls:
    - hosts:
        - ksox.exchange
        - www.ksox.exchange
      secretName: ksox-exchange-tls
  rules:
  - host: ksox.exchange
  - host: www.ksox.exchange
