[workspace]

members = [
    "blockchain",
    "engagement",
    "engine",
    "types/evm",
    "types/fraction",
    "types/infinity",
    "types/macros",
    "types/pricelevel",
    "types/value",
    "worker",
]
