[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.check]
script = "cargo check --release"

[tasks.build]
script = "cargo build --release"

[tasks.fmt]
script = "cargo fmt"

[tasks.clippy]
script = "cargo clippy"

[tasks.sort]
script = "cargo sort -w"

[tasks.udeps]
script = "cargo udeps"

[tasks.test]
script = "cargo test --release"

[tasks.sqlx-prepare]
script = "cargo sqlx prepare --workspace --database-url postgresql://ksoxuser:ksoxuserp4ssword@localhost/ksox"

[tasks.clean]
script = "cargo clean"

[tasks.delete_postgres]
script = "sudo docker compose rm -vsf postgres"

[tasks.run_postgres]
script = "sudo docker compose up --wait postgres"

[tasks.stop_postgres]
script = "sudo docker compose stop postgres"

[tasks.default]
alias = "total"

[tasks.sqlx]
dependencies = [
    "delete_postgres",
    "run_postgres",
    "sqlx-prepare",
    "stop_postgres",
]

[tasks.total]
dependencies = [
    "delete_postgres",
    "run_postgres",
    "clean",
    "fmt",
    "sort",
    "sqlx",
    "build",
    "check",
    "clippy",
    "test",
    # "udeps",
]
