[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.check]
script = "cargo check --release"

[tasks.build]
script = "cargo build --release"

[tasks.fmt]
script = "cargo fmt"

[tasks.clippy]
script = "cargo clippy"

[tasks.sort]
script = "cargo sort -w"

[tasks.udeps]
script = "cargo udeps"

[tasks.test]
script = "cargo test --release"

[tasks.clean]
script = "cargo clean"
dependencies = [
    { name = "clean", path = "engagement" },
    { name = "clean", path = "engine" },
    { name = "clean", path = "fraction" },
    { name = "clean", path = "worker" },
    { name = "clean", path = "pricelevel" },
]

[tasks.delete_postgres]
script = "sudo docker compose rm -vsf postgres"

[tasks.run_postgres]
script = "sudo docker compose up --wait postgres"

[tasks.stop_postgres]
script = "sudo docker compose stop postgres"

[tasks.default]
alias = "total"

[tasks.sqlx]
dependencies = [
    "delete_postgres",
    "run_postgres",
    { name = "sqlx", path = "engagement" },
    { name = "sqlx", path = "engine" },
    { name = "sqlx", path = "worker" },
    "stop_postgres",
]

[tasks.total]
dependencies = [
    "delete_postgres",
    "run_postgres",
    "fmt",
    "sort",
    { name = "sqlx", path = "engagement" },
    { name = "sqlx", path = "engine" },
    { name = "sqlx", path = "worker" },
    "build",
    "check",
    "clippy",
    "test",
    "udeps",
]
