[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.2", features = ["http2", "headers"] }
futures = "0.3"
headers = "0.3"
oauth2 = "4.3"
http = "0.2"
tokio-stream = "0.1"
serde = "1.0"
tokio = { version = "1.24", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
redis = { version = "0.22", features = ["tokio-comp"] }
anyhow = "1.0.68"
ethereum-types = "0.14.1"