[package]
name = "worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.68"
async-stream = "0.3.4"
axum = { version = "0.6.2", features = ["http2", "headers"] }
bytes = "1.3.0"
cache = { path = "../cache" }
database = { path = "../database" }
ethereum-types = "0.14.1"
ethers-core = "1.0.2"
futures = "0.3.25"
headers = "0.3.8"
http = "0.2.8"
ordered-float = { version = "3.4.0", features = ["serde"] }
prefix-hex = "0.5.0"
rand = "0.8.5"
regex = "1.7.1"
serde = "1.0.152"
serde_with = "2.2.0"
strsim = "0.10.0"
tokio = { version = "1.24.1", features = ["full"] }
tokio-stream = "0.1.11"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
