apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-blockchain-deployment
  namespace: ksox-finance
  labels:
    app: server-blockchain
spec:
  selector:
    matchLabels:
      app: server-blockchain
  template:
    metadata:
      labels:
        app: server-blockchain
    spec:
      containers:
        - name: server-blockchain
          image: registry.internal.visoft.solutions/server-blockchain
          envFrom:
            - secretRef:
                name: envs
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 400Mi
              cpu: 400m
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres-service 5432; do echo waiting for postgres; sleep 1.$((RANDOM % 100)); done;",
            ]
        - name: wait-for-redis
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z redis-service 6379; do echo waiting for redis; sleep 1.$((RANDOM % 100)); done;",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: server-blockchain-service
  namespace: ksox-finance
spec:
  selector:
    app: server-blockchain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
