apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-engagement-deployment
  namespace: prod-ksox-finance
  labels:
    app: server-engagement
spec:
  selector:
    matchLabels:
      app: server-engagement
  template:
    metadata:
      labels:
        app: server-engagement
    spec:
      containers:
      - name: server-engagement
        image: server-engagement
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        env:
        - name: DATABASE_URL
          value: postgresql://ksoxuser:ksoxuserp4ssword@postgres-service/ksox
        - name: ENGINE_FRACTION_ACCURACY
          value: 1/10000
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 1; done;']
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z redis-service 6379; do echo waiting for redis; sleep 1; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: server-engagement-service
  namespace: prod-ksox-finance
spec:
  selector:
    app: server-engagement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
