apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-engine-deployment
  labels:
    app: server-engine
spec:
  selector:
    matchLabels:
      app: server-engine
  template:
    metadata:
      labels:
        app: server-engine
    spec:
      containers:
      - name: server-engine
        image: server-engine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        env:
        - name: DATABASE_URL
          value: postgresql://ksoxuser:ksoxuserp4ssword@postgres-service/ksox
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z redis-service 6379; do echo waiting for redis; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: server-engine-service
spec:
  selector:
    app: server-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
