apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-engine-deployment
  namespace: ksox-finance
  labels:
    app: server-engine
spec:
  selector:
    matchLabels:
      app: server-engine
  template:
    metadata:
      labels:
        app: server-engine
    spec:
      containers:
        - name: server-engine
          image: server-engine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 500Mi
              cpu: 500m
          env:
            - name: KSOX_SERVER_BLOCKCHAIN_URL
              value: "http://ksox-server-blockchain/"
            - name: KSOX_WS_BLOCKCHAIN_URL
              value: "ws://ksox-blockchain:8545/"
            - name: KSOX_POSTGRES_URL
              value: "postgresql://ksoxuser:ksoxuserp4ssword@ksox-postgres/ksox"
            - name: KSOX_REDIS_URL
              value: "redis://ksox-redis/"
            - name: KSOX_SERVER_ENGINE_URL
              value: "http://ksox-server-engine/"
            - name: CONTRACT_PRIVATE_KEY
              value: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
            - name: CONTRACT_ADDRESS
              value: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
            - name: DEPOSIT_CONFIRMATIONS
              value: "5"
            - name: TESTS_CASES
              value: "10000"
            - name: TESTS_FRACTION_BYTES
              value: "2"
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres-service 5432; do echo waiting for postgres; sleep 1.$((RANDOM % 100)); done;",
            ]
        - name: wait-for-redis
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z redis-service 6379; do echo waiting for redis; sleep 1.$((RANDOM % 100)); done;",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: server-engine-service
  namespace: ksox-finance
spec:
  selector:
    app: server-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
