apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: server-worker-daemonset
  namespace: ksox-finance
  labels:
    app: server-worker
spec:
  selector:
    matchLabels:
      app: server-worker
  template:
    metadata:
      labels:
        app: server-worker
    spec:
      containers:
        - name: server-worker
          image: server-worker
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 500Mi
              cpu: 500m
          env:
            - name: KSOX_SERVER_BLOCKCHAIN_URL
              value: "http://ksox-server-blockchain/"
            - name: KSOX_WS_BLOCKCHAIN_URL
              value: "ws://ksox-blockchain:8545/"
            - name: KSOX_POSTGRES_URL
              value: "postgresql://ksoxuser:ksoxuserp4ssword@ksox-postgres/ksox"
            - name: KSOX_REDIS_URL
              value: "redis://ksox-redis/"
            - name: KSOX_SERVER_ENGINE_URL
              value: "http://ksox-server-engine/"
            - name: CONTRACT_PRIVATE_KEY
              value: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
            - name: CONTRACT_ADDRESS
              value: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
            - name: DEPOSIT_CONFIRMATIONS
              value: "5"
            - name: TESTS_CASES
              value: "10000"
            - name: TESTS_FRACTION_BYTES
              value: "2"
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres-service 5432; do echo waiting for postgres; sleep 1.$((RANDOM % 100)); done;",
            ]
        - name: wait-for-redis
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z redis-service 6379; do echo waiting for redis; sleep 1.$((RANDOM % 100)); done;",
            ]
        - name: wait-for-engine
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z server-engine-service 80; do echo waiting for engine; sleep 1.$((RANDOM % 100)); done;",
            ]
        - name: wait-for-engagement
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z server-engagement-service 80; do echo waiting for engagement; sleep 1.$((RANDOM % 100)); done;",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: server-worker-service
  namespace: ksox-finance
spec:
  selector:
    app: server-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-worker-ingress
  namespace: ksox-finance
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: ingress-nginx-prod
  tls:
    - hosts:
        - app.ksox.finance
        - pay.ksox.finance
        - dashboard.ksox.finance
      secretName: ksox-finance-tls
  rules:
    - host: app.ksox.finance
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-worker-service
                port:
                  number: 80
    - host: pay.ksox.finance
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-worker-service
                port:
                  number: 80
    - host: dashboard.ksox.finance
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-worker-service
                port:
                  number: 80
