apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-worker-deployment
  labels:
    app: server-worker
spec:
  selector:
    matchLabels:
      app: server-worker
  template:
    metadata:
      labels:
        app: server-worker
    spec:
      containers:
      - name: server-worker
        image: server-worker
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        env:
        - name: DATABASE_URL
          value: postgresql://ksoxuser:ksoxuserp4ssword@postgres-service/ksox
        - name: ENGINE_URL
          value: http://server-engine-service/
        - name: REDIS_URL
          value: redis://redis-service/
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z redis-service 6379; do echo waiting for redis; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: server-worker-service
spec:
  selector:
    app: server-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-worker-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
      - www.ksox.exchange
      secretName: www-ksox-exchange-tls
  rules:
  - host: www.ksox.exchange
    http:
      paths:
      - path: /app/api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: server-worker-service
            port:
              number: 80
