apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-landing-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: web-landing-service
                port:
                  number: 80
