apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-landing-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /landing
        pathType: Prefix
        backend:
          service:
            name: web-landing-service
            port:
              number: 80
