apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: ksox-finance
  labels:
    app: redis-database
spec:
  selector:
    matchLabels:
      app: redis-database
  template:
    metadata:
      labels:
        app: redis-database
    spec:
      volumes:
        - name: redis-pv-storage
          persistentVolumeClaim:
            claimName: redis-pv-claim
      containers:
        - name: redis-database
          image: registry.internal.visoft.solutions/redis-database
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: "/data"
              name: redis-pv-storage
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ksox-finance
spec:
  selector:
    app: redis-database
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
