apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: prod-ksox-finance
  labels:
    app: redis-database
spec:
  selector:
    matchLabels:
      app: redis-database
  template:
    metadata:
      labels:
        app: redis-database
    spec:
      containers:
      - name: redis-database
        image: redis-database
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: prod-ksox-finance
spec:
  selector:
    app: redis-database
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
